# Generated by Django 4.1.5 on 2023-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyData',
            fields=[
                ('number', models.IntegerField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
