# Generated by Django 4.1.5 on 2023-01-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummydata',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
